#Stage 1: Builder
FROM python:3.12-slim AS builder

WORKDIR /build

#PYTHONDONTWRITEBYTECODE=1: Prevents useless .pyc files.
#PYTHONUNBUFFERED=1: logs are shown directly inside terminal, for easy debugging.
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

#Isolating dependencies
RUN python -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Runtime
FROM python:3.12-slim AS runtime

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/opt/venv/bin:$PATH"

# creating a group "app" and user "app" (non-root)
RUN addgroup --system app && \
    adduser --system --ingroup app app

WORKDIR /app

#copying the virtual environment folder from builder stage to runtime stage to get necessary dependencies
COPY --from=builder /opt/venv /opt/venv

COPY . .

#changing the ownership of all files in /app to the "app" user
RUN chown -R app:app /app

#switching the active runtime user from "root" to "app"
USER app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]